# Generated by Django 5.1.5 on 2025-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='scrapentry',
            name='workplace',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='workplace',
            field=models.CharField(default='Nie dotyczy', max_length=50, verbose_name='Miejsce pracy'),
        ),
    ]
